global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
    builders:
      # json_serializable:
      #   options:
      #     include_if_null: false
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers"
          output_folder: "lib/api"
